### ISSUE TITLE
Responsive gutters for Grid component

### ISSUE THREAD

**Issue by simonlayfield** [N00nDay/stwui#114]
It'd be a worthwhile feature to have control over the gutter size(s) passed to a Row component across multiple viewports.

I had some success testing out multiple arrays being passed through and converting those to tailwind margin/padding classes, but hit an issue whereby since the classes are dynamic they're missed by the compiler and excluded from the build.

An example of responsive columns for the grid component in the docs would also be useful, providing responsive gutters can be achieved.

**Comment by simonlayfield** [comment]
My solution for this for now is to avoid using `gutter` and to simply use tailwind padding classes on `Col` and negative margin classes on the `Row` for each desired viewport, bolstered by `!important` to overpower the inline styles applied.

```
    <Row align="center" class="md:!-mx-4">
    	<Col class="col-24 md:col-12 md:!px-4 text-left">
    	   <!-- column 1 -->
    	</Col>
    	<Col class="col-24 md:col-12 md:!px-4 text-left ">
    	   <!-- column 1 -->
    	</Col>
    </Row>
```

**Comment by N00nDay** [comment]
The example for the responsive `Grid` is pretty straightforward. The responsive `gutter`, `justify`, and `align` properties are going to be a little more complex.

I haven't given this a ton of thought yet but in order for `gutter`, `justify`, and `align` to be responsive as it sits it would have to be done via javascript. My concern with this is not wanting to box users into specific breakpoints/screen sizes but allowing them to customize as they see fit but not have to update both tailwind CSS and some javascript config. I will figure it out just need a minute to think it over.

**Comment by N00nDay** [comment]
I am reconsidering supporting the Grid component. This component is just a glorified flex container. As it currently sits the component provides some ease of use but as this issue has been pointed out it is fairly rigid and inflexible (pun intended). Because TailwindCSS classes cannot be calculated (ie. ``py-${gutter}``) this makes the process of accounting for every possible gutter scenario an arduous task and not exactly worth it in my opinion. Using your examples you can achieve this with regular HTML elements like so:

```
<div class="relative box-border flex justify-center mx-0 md:-mx-4">
    <div class="col-24 md:col-12 px-0 md:px-4 text-left">
        <!-- column 1 -->
    </div>
    <div class="col-24 md:col-12 px-0 md:px-4 text-left">
        <!-- column 2 -->
    </div>
</div>
```

TailwindCSS examples of Grid solve about 50% of the use cases that STWUI Grid components cover. An example can be found [here](https://tailwindcss.com/docs/grid-template-columns). I have adapted the example from this website to be a drop-in replacement for your example:

```
<div class="grid grid-cols-2 md:gap-4">
  <div class="text-left">01</div>
  <!-- ... -->
  <div class="text-left">09</div>
</div>
```

Ultimately, I am not a fan of this response. I am starting to lean more in the direction of a pure component library and to leave layout UI out of the library entirely as it will confine developers rather than simplify life and allow flexibility. If we do take this path the `Grid` component would be the only component affected, I would leave the `Layout` component as a take it or leave it layout UI.

I will leave this issue open and not remove the `Grid` component for a few days to give you or anyone else the ability to provide feedback.
