### ISSUE TITLE
TimeScheduler Component

### ISSUE THREAD

**Issue by MrWildanMD** [N00nDay/stwui#177]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

![image](https://github.com/N00nDay/stwui/assets/60354284/802b59dd-eaf1-4d30-a44f-b09ceb45dafe)
Okay after discussing with my team,,we need to handle the time/querying the time, like the image attached,,is this possible or if not maybe this is feature request

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

You can refer to: https://sisiranelite.com/book/ 
for example choose the following in the website
Locations: Menteng Atas
Service: Choose Anything
Hair Artists: Mr Pani

then you'll see the datepicker like i mentioned in feature request

**Comment by N00nDay** [comment]
Your proposal is not something that will be included in this library.

 Another option is adding a standalone TimePicker or possibly a standalone Scheduler component. The TimePicker is pretty straightforward but the Scheduler component would be an embed rather than an input and the layout would look like below, with styling updates to match STWUI.

![Screenshot 2023-10-06 at 7 47 18 AM](https://github.com/N00nDay/stwui/assets/28783829/8d99b199-5ff6-453e-b536-3d3fcdc4301a)

Would something like this meet your needs?

**Comment by MrWildanMD** [comment]
Yes that's it, so i can control which time is enabled/disabled according to query...if that does'nt exists can you provide link to that component?

**Comment by N00nDay** [comment]
It doesn't exist but that could be a good addition to the library. I am not sure on a timeline at this point but I can put it in the works. That was just a screenshot of something I found online that is close to what I have in my head.

**Comment by MrWildanMD** [comment]
Yes, that was exactly what i was looking for, and my thought was datepicker can do such things...maybe for now i'll using standalone component like you said

**Comment by MrWildanMD** [comment]
welp, i found alternative that is actually i'm creating a child view when i select date then fetching query then render the child view which is time schedule that still available, but i hope it will become one of stwui component

**Comment by N00nDay** [comment]
With you finding a solution that I would argue is probably the best option for most devs as it provides the necessary flexibility required for a complex/specialized component of this nature I am going to close this one out. Cheers!
