### ISSUE TITLE
First option is keeping gray background color even though it is not selected one.

### ISSUE THREAD

**Issue by hardcommitoneself** [N00nDay/stwui#179]
### Current Behavior

I have selected the third one, but the first one has still gray background. 

![image](https://github.com/N00nDay/stwui/assets/104041595/65987c85-2a46-46fc-a8b4-0de3b09949de)

### Expected Behavior

Any non-selected options shouldn't have special background.

**Comment by N00nDay** [comment]
The grey background does not indicate that an option is selected. The check mark and bold text is what indicates that an option is selected.

The background is focus indicator. The reason the first option is highlighted when opening the select/dropdown has to do with keyboard usability. Every input in STWUI can be used directly from your keyboard like their html counterparts allowing for a user to never have to use a mouse.  

In html you would see the option with a ring around it instead of the highlighting behavior of STWUI.

**Comment by N00nDay** [comment]
This is in the works and should be resolved today.
